/**/carla_camera_publisher:  
  ros__parameters:
    rgbcam/x : 2.0
    rgbcam/y : 0.0
    rgbcam/z : 3.5
    rgbcam/pitch : -15.0 
    rgbcam/yaw : 0.0
    rgbcam/roll : 0.0
    rgbcam/sensor_tick : "0.033333f"

/**/carla_radar_publisher:  
  ros__parameters:
    radar/x : 2.3
    radar/y : 0.0
    radar/z : 1.5
    radar/pitch : 0.0 
    radar/yaw : 0.0
    radar/roll : 0.0
    radar/sensor_tick : "0.1f"
    radar/horizontal_fov : "60.0f"
    radar/vertical_fov : "5.0f"
    radar/points_per_second : "20000"
    radar/range : "100.0f"

/**/carla_lidar_publisher:  
  ros__parameters: 
    lidar/x : 2.3
    lidar/y : 0.0
    lidar/z : 1.5
    lidar/pitch : 0.0 
    lidar/yaw : 0.0
    lidar/roll : 0.0
    lidar/sensor_tick : "0.1f"
    lidar/horizontal_fov : "180.0f"
    lidar/upper_fov : "30.0f"
    lidar/lower_fov : "-10.0f"
    lidar/points_per_second : "57000"
    lidar/range : "100.0f"